### ISSUE TITLE
Wrong latest post in blog section

### ISSUE THREAD

**Issue by pmviva** [hivickylai/hugo-theme-introduction#15]
I found an issue in the blog section regarding latest post. Apparently it shows the first post written as the latest post.

I guess the problem is in layouts/blog/list.html layout:

{{ range first 1 (where .Data.Pages.ByPublishDate .Reverse "Section" "blog") }} 

should be instead of

{{ range first 1 (where .Data.Pages.ByPublishDate "Section" "blog") }} 

![screenshot_2017-12-03_20-54-17](https://user-images.githubusercontent.com/15917353/33531488-8e048bb8-d86c-11e7-8d03-6ec86dbb97fe.png)

**Comment by hivickylai** [comment]
There seems to be a change between Hugo versions 0.25 and 0.31. I was not able to reproduce this issue in Hugo v0.25 (the latest post shown was correct). I *was* able to reproduce it in v0.31 (the latest post was the oldest post).

Since I've updated the theme to support v0.30 as the minimum Hugo version, I'll implement this change.
