### ISSUE TITLE
modify css

### ISSUE THREAD

**Issue by lupa18** [hivickylai/hugo-theme-introduction#28]
Hello ! could you suggest some friendly way to modify the css in documentation?

I'm not css expert and I try to do it but it's very difficult because it not has a "friendly" format. 

Thanks in advance !

**Comment by hivickylai** [comment]
Hi @lupa18! In its current state, the theme's CSS is not easily modified. It's built using Sass and Bulma, and minified. I'd like to simplify this in the future so that it can be easily modified. You can read Issue #29 for more on that.

I will say that if you run the minified CSS through a beautify processor, it will space everything out so that it's easier to read. I use Visual Studio Code, which has many extensions available for beautifying code.
